### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by wilsonehusin** [Nicholas2750/light-novel-parser#2]
1. Let's use [Fire][fire-repo] for better usability.
    * Acceptance criteria: `python [app_name].py url_of_target` (consider renaming app name? `novelp`?
1. Possibly [make it installable][cookie-cutter-repo] with `pip` . This will also add the basics like `requirements.txt`, `README.md`, `CONTRIBUTING.md`, `CHANGESET.md`, etc.
    * Acceptance criteria: installable with `pip install light-novel-parser`

[cookie-cutter-repo]: https://github.com/wdm0006/cookiecutter-pipproject
[fire-repo]: https://github.com/google/python-fire

**Comment by wilsonehusin** [comment]
I think the two things are kind of intertwined, but if it's easier to split into 2 issues we can do that later.

**Comment by Nicholas2750** [comment]
I'll probably use Fire and make it installable with pip once the parser is more refined.

Ideally, I want to do those after I can make just one script that would work on most websites (I'm still separating them currently so it's easier to debug) with some features that I think would be nice to have (parse the novel into a dark background with white text format).
